### ISSUE TITLE
Layout-Verwaltung/Voreinstellung: Findet Verzeichnis nicht

### ISSUE THREAD

**Issue by bjsvwcur** [opengisch/QGIS-Issues-SO#1]
Unter «Projekt/Vorlagenverzeichnis öffnen» gibt der Klick auf  «Voreinstellung» folgende Fehlermeldung aus: «Konnte Verzeichnis "C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./composer_templates" nicht öffnen oder erzeugen.»
![LayoutManager_Fehlermeldung](https://user-images.githubusercontent.com/38523407/58329207-4c005480-7e34-11e9-9bad-e32402813d5c.PNG)

Sollte es das Verzeichnis nicht bei der Installation von QGIS automatisch anlegen, muss das nachträglich manuell angelegt werden oder kann das irgendwo eingestellt werden?
![LayoutManager_Verzeichnis](https://user-images.githubusercontent.com/38523407/58329354-a6011a00-7e34-11e9-98d8-88a31bd494f9.PNG)

Danke und Gruss
Sandra

QGIS-Version | 3.4.5-Madeira
QGIS-Codeversion | 89ee6f6e23

**Comment by m-kuhn** [comment]
Gute Frage, ich habe diesen Knopf bisher weder entdeckt noch benutzt, aber er funktioniert bei mir ebenfalls nicht.

So wie es aussieht wäre er gedacht für Vorlagen, welche bei der Installation ausgeliefert werden, aber momentan werden von Haus aus keine ausgeliefert. Wir gehen dem nach...

**Comment by m-kuhn** [comment]
Fix in QGIS 3.4 und master implementiert.
Weiterhin wird als erstes nach dem Verzeichnis in der Fehlermeldung oben gesucht. Falls dies nicht existiert wird das erste Verzeichnis aus der Liste in den QGIS Einstellungen --> Layout --> Vorlageverzeichnisse geöffnet. Falls dort nichts konfiguriert ist wird der Knopf ausgeschaltet. Ein Tooltip auf dem Knopf gibt Anweisungen, wie die Konfiguration gemacht werden kann.
