### ISSUE TITLE
Standardeinstellung für den Cache

### ISSUE THREAD

**Issue by bjsvwcur** [opengisch/QGIS-Issues-SO#2]
Die Standardeinstellung für den Cache darf nicht auf …\AppData\Roaming\..., sondern muss auf …\AppData\Local\... zeigen. (Nach meinen Kenntnissen macht dies z.B. Firefox standardmässig genau so.)
Kann das Irgendwo eingestellt werden im QGIS??

QGIS-Version | 3.4.5-Madeira 
QGIS-Codeversion | 89ee6f6e23

**Comment by m-kuhn** [comment]
Zum kompletten Verständnis: AppData\Roming ist aus welchem Grund nicht ok? Damit das auf der lokalen Festplatte liegt und nicht übers Netz transportiert wird?

Klingt für mich nach etwas, was ggf. am besten in QGIS selbst angepasst werden sollte (daher bin ich froh um gute Argumente für die Frage oben).

In der Zwischenzeit kann dies für euch über `qgis_global_settings.ini` folgendermassen gelöst werden:

```
[cache]
directory=C:\Pfad\zu\einem\geeigneten\Ort
```

**Comment by schmandr** [comment]
Ja, genau: Unsere Nutzer arbeiten auf Windows-Servern (sie verbinden sich dorthin mit Citrix). Bei jedem Login landen sie auf einem anderen Server. Alles, was in AppData\Roaming ist, wird beim Login von einem zentralen Datenserver auf den Server in ihr Home herunterkopiert, damit sie ihre Einstellungen etc. wieder haben. Wenn sie sich ausloggen, wird AppData\Roaming wieder auf den Datenserver kopiert. Dies ist für Cache-Daten nicht notwendig, und wegen der Down- und Upload-Zeit (Login dauert u.U. länger) und dem Speicherplatzverbrauch auf dem zentralen Server auch nicht wünschenswert. Deshalb sollen sie nach AppData\Local. So werden sie nach dem Ausloggen nicht auf den Datenserver kopiert. Mit dem minimen Nachteil, dass sie in der nächsten Session neu gecacht werden müssen.

**Comment by m-kuhn** [comment]
Danke für die Rückmeldung, die Implementation wurde gemacht.
Frage: muss dies zurückportiert werden oder funktioniert es für euch mit dem oben beschriebenen Ansatz über die `qgis_global_settings.ini` bis zum Update auf den nächsten LTR (3.10)?

**Comment by m-kuhn** [comment]
Implementiert in master, Backport 3.4 pending

**Comment by m-kuhn** [comment]
Implementiert in 3.4
