### ISSUE TITLE
Verbindung zu PostGIS mit SSL-Verschlüsselung nicht möglich, wenn man Benutzername/Passwort in der QGIS Authentication Database gespeichert hat

### ISSUE THREAD

**Issue by bjsvwcur** [opengisch/QGIS-Issues-SO#3]
Ausgangslage: Eine PostGIS-DB, die so konfiguriert ist, dass man die Verbindung mit SSL herstellen muss (Zeile "hostssl ... md5" in pg_hba.conf)

Wenn man in QGIS eine Verbindung zu dieser DB anlegt (mit SSL mode "require") und sich verbindet, wird man nach Benutzername und Passwort gefragt, danach wird die Verbindung hergestellt. Dies funktioniert so korrekt.

Wenn man die DB-Verbindung in QGIS so einstellt, dass Benutzername und Passwort aus der QGIS Authentication Database ausgelesen werden sollen, kann die Verbindung zur DB nicht direkt hergestellt werden, sondern man wird trotzdem nach Benutzername und Passwort gefragt. Im Dialog, wo man danach gefragt wird, steht u.a. die Meldung "SSL error: certificate verify failed".

Wahrscheinlich versucht QGIS bei dieser Kombination "Verbindung mit SSL + Credentials aus der QGIS Authentication Database", sich mit einem SSL-Key oder -Zertifikat an der DB anzumelden. Es sollte aber nicht mit einem Key, sondern weiterhin mit Benutzername/Passwort (aus der QGIS Authentication Database) anmelden, die Verbindung aber mit SSL verschlüsseln.

QGIS Windows
QGIS-Version | 3.4.5-Madeira
QGIS-Codeversion | 89ee6f6e23

**Comment by m-kuhn** [comment]
Ich kann das Problem so bestätigen, die Ursache dafür aber noch nicht genau isolieren.
Weitere Informationen folgen, sobald wir mehr wissen. Falls für euch die Priorität hoch ist, lasst uns das bitte wissen, damit wir das entsprechend behandeln können.

**Comment by m-kuhn** [comment]
Die Situation ist momentan wie folgt:

Sobald mit der Authentication Database gearbeitet wird, produziert QGIS im Hintergrund automatisch ein `sslrootcert` Parameter beim Verbindungsaufbau. Dieser kann dazu verwendet werden, die Gültigkeit des Server-SSL-Zertifikats zu überprüfen.

In Kombination mit der folgenden Notiz aus der [PostgreSQL Dokumentation](https://www.postgresql.org/docs/9.1/libpq-ssl.html) führt das dazu, dass bei der Einstellung sslmode=require diese Überprüfung automatisch durchgeführt wird.

> Note: For backwards compatibility with earlier versions of PostgreSQL, if a root CA file exists, the behavior of sslmode=require will be the same as that of verify-ca, meaning the server certificate is validated against the CA. Relying on this behavior is discouraged, and applications that need certificate validation should always use verify-ca or verify-full.

# Möglichkeiten

## Signierten Serverschlüssel verwenden

Der momentan verwendete SSL-Schlüssel auf dem Server ist höchstwahrscheinlich selbst-signiert und die Signatur in der QGIS Installation nicht als vertrauenswürdige Signatur eingetragen. Dies zu beheben wäre die sicherste Variante, konkret können damit "man in the middle attacks" verhindert werden.

## Umstellen auf sslmode=prefer

Wenn auf sslmode=prefer umgestellt wird, wird nach Möglichkeiten nach wie vor SSL verwendet (was in diesem Fall hier geschehen wird, da der Server dies anbietet), jedoch das oben zitierte Verhalten nicht ausgelöst. Somit ist es weiterhin möglich, sich auf einen Server mit selbst erstelltem Schlüssel zu verbinden.

# Bugfix in QGIS

Ich habe eine Diskussion angestossen, um das Verhalten von QGIS zu ändern und bei der Konfiguration von sslmode=require keine Schlüsselverifizierung zu erzwingen.

**Comment by schmandr** [comment]
Danke für die Nachforschungen. Unsere Idee ist es schon, sslmode=prefer zu verwenden, aber es tritt eben auch damit auf. Ich habe nur als Beispiel sslmode=require geschrieben, damit es sicher klar ist, dass SSL zum Einsatz kommt.

Priorität ist "leicht erhöht", weil sich damit häufiges Passworteingeben vermeiden liesse, was den Benutzern weniger Anlass zum Rüsseln gäbe.

**Comment by m-kuhn** [comment]
Zur Information: wir haben bereits einen Fix, momentan fehlt hauptsächlich noch die inbetriebnahme der entsprechenden Unit Tests, was sich leider als nicht trivial erweist. Und die Evaluation einer Rückportierung auf 3.4.

**Comment by m-kuhn** [comment]
Umgesetzt in master, inklusive Wiederinbetriebnahme und Erweiterung Unit Tests für Postgres + SSL.

TODO: Backport auf 3.4

**Comment by m-kuhn** [comment]
Backport pull request pending

**Comment by m-kuhn** [comment]
Backport 3.4 merged.
