### ISSUE TITLE
Neues Projekt: Einstellung (Messungen, Ellipsoid) 

### ISSUE THREAD

**Issue by bjsvwcur** [opengisch/QGIS-Issues-SO#4]
Wenn ein neues QGIS Projekt erstellt wird, steht in den Projekteigenschaften/Allgemein/Ellipsoid immer "Bessel 1841".
Das Ellipsoid sollte Standartmässig (Einstellungen/Optionen) für ein neues Projekt auf "None/Planimetric" gesetzt werden können. 
Unter Einstellungen/Optionen habe ich nichts dergleichen gefunden.

-------------------------------
QGIS-Version: 3.4.9-Madeira
QGIS-Codeversion: 54585165bb

**Comment by m-kuhn** [comment]
Mit der aktuellsten QGIS 3.4 wurde die Möglichkeit integriert, "Kein KBS / Nicht-Erde KBS" als Standard zu setzen. Damit wird auch das Ellipsoid auf None/Planimetric gesetzt.

Ansonsten wird beim Erstellen eines neuen Projektes das Ellipsoid auf das durch das Standard-KBS vorgegebene Ellipsoid gesetzt.

Was nicht analog zu diesem Ansatz funktioniert ist, wenn die Option "Auf KBS von erstem geladenen Layer setzen" aktiviert wird. In diesem Fall wird das Ellipsoid nicht analog zum gesetzten KBS angepasst (wie es meiner Meinung nach sollte).

Frage:

 - Muss der Standardwert für das Ellipsoid unabhängig vom KBS gesteuert werden können?

Das setzen des Ellipsoid beim Setzen des KBS des ersten geladenen Layers sehe ich mir gerade noch an.

**Comment by bjsvwcur** [comment]
In Unserer QGIS Enterprise Version können wir unter den Optionen folgende Einstellungen machen:
![grafik](https://user-images.githubusercontent.com/38523407/61515350-b1bb2800-aa02-11e9-9d61-0506c5e4bc1a.png)

"Spontanprojektion nicht einschalten" hat zur Folge das in den Projekteigenschaften das Ellipsoid deaktiviert ist.
![grafik](https://user-images.githubusercontent.com/38523407/61515387-c7305200-aa02-11e9-9862-ec8a1cb91baa.png)

Mit der nei integrierten Möglichkeit  "Kein KBS / Nicht-Erde KBS" als Standard zu setzen, sollte mein Anliegen gelöst sein. Ich werde es noch abklären.

**Comment by m-kuhn** [comment]
Am besten noch kurz mit @schmandr rückbesprechen, wir hatten eine längere Diskussion vor kurzem.

**Comment by bjsvwcur** [comment]
Habe ich gerade festgestellt.... :-)

**Comment by bjsvwcur** [comment]
Ich habe jetzt auch gesehen das man "kein KBS" setzen kann. Ich werde es nächste Woche testen.
Sorry für die Umstände. Ticket kann geschlossen werden.
Danke!

**Comment by m-kuhn** [comment]
Danke fürs Testen, ich freue mich auf die Resultate.
Das Problem mit dem Ellipsoid beim "KBS von erstem Layer übernehmen" wurde gelöst (respektive Pull Request dafür geöffnet)
