### ISSUE TITLE
Fehler beim Flächenmessen (Werkzeug Messen)

### ISSUE THREAD

**Issue by bjsvwcur** [opengisch/QGIS-Issues-SO#5]
Ausgangslage:
Ein Flächenobjekt mit 10'000m2 Fläche.
![Flaeche_Kartesisch](https://user-images.githubusercontent.com/38523407/61465079-ae2e8f00-a977-11e9-959d-eaefd9f8db14.PNG)
<br>
Wenn man im Werkzeug "Fläche Messen" die Fläche abmisst und mit der rechten Maustaste irgendwo im Kartenausschnitt abschliesst, wird der letzte Klickpunkt nicht angezeigt, aber in der Flächenrechnung mit einbezogen:
![Flaeche_gemessen2](https://user-images.githubusercontent.com/38523407/61464951-73c4f200-a977-11e9-9756-69f8e5672736.PNG)
<br>
Resultat nach Rechts-Klick (Fläche sollte ~10'000m2 sein):
![Flaeche_gemessen](https://user-images.githubusercontent.com/38523407/61465310-1bdabb00-a978-11e9-82e9-68b0a5e14c90.PNG)
<br>
Beispieldaten Gemäss Bilder:
[FlaecheMessen.zip](https://github.com/opengisch/QGIS-Issues-SO/files/3406882/FlaecheMessen.zip)

-------------------------------
QGIS-Version: 3.4.9-Madeira
QGIS-Codeversion: 54585165bb

**Comment by m-kuhn** [comment]
In den Projekteigenschaften kann eingestellt werden, ob die Berechnung auf dem Ellipsoid oder planimetrisch gemacht werden soll.

Im angehängten Beispielprojekt ist das Bessel-Ellipsoid eingestellt, die Erwartung von dir aber planimetrisch. Das Projekt muss wie unten angepasst werden.

Ab der Version QGIS 3.10 wird es auch möglich sein, QGIS so einzustellen, dass neue Projekte automatisch mit planimetrisch konfiguriert werden. Bis dahin muss das noch manuell gemacht werden.

![Screenshot from 2019-08-06 14-33-00](https://user-images.githubusercontent.com/588407/62540146-31485400-b857-11e9-9fc1-1ea377a2fce9.png)

Sollen wir uns die andere Sache mit dem "letzten Punkt" noch ansehen?

**Comment by bjsvwcur** [comment]
Hoi Matthias

Danke für die Rückmeldung.
Das Problem tritt auch auf wenn für die Berechnung planimetrisch eingestellt ist.
Das Problem ist der letzte "Mausklick" (Beenden mit Rechts Klick). Wenn dieser nicht auf dem letzten Eckpunkt liegt.
Der letzte Klickpunkt wird nicht angezeigt, aber in der Flächenrechnung mit einbezogen.

**Comment by m-kuhn** [comment]
Ah sorry, dann habe ich das falsch verstanden.
Schauen wir uns an!

**Comment by bjsvwcur** [comment]
Supi und Danke:-)

**Comment by m-kuhn** [comment]
Bestätigt, Fix pending

**Comment by m-kuhn** [comment]
Eingepflegt in master, backports 3.4 und 3.8 warten noch etwas um bei allfälligen Problemen reagieren zu können.

**Comment by bjsvwcur** [comment]
Passt so. Danke

**Comment by m-kuhn** [comment]
Integriert in 3.4.11, 3.8.2, 3.10.0
Danke fürs Melden!
