### ISSUE TITLE
Attribut mit Typ "boolean": Wert "false" wird in der Attributtabelle nicht angezeigt

### ISSUE THREAD

**Issue by bjsvwcur** [opengisch/QGIS-Issues-SO#7]
Wenn ein Attribut vom Typ "boolean" ist, wird im QGIS in der Attributtabelle der Wert 0="false" nicht angezeigt. Der Wert 1="true" wird angezeigt. Siehe folgende Bilder.

Layereigenschaften/Quellfelder: Attribut "Inactive"<br>
![grafik](https://user-images.githubusercontent.com/38523407/64610797-59841f00-d3d0-11e9-9570-9df9560727f6.png)

Beim Wert "Inactive" wird im QGIS nichts angezeigt:<br>
![grafik](https://user-images.githubusercontent.com/38523407/64610953-a10aab00-d3d0-11e9-94a9-a5d930e8e372.png)

Screen aus der Datenbank: Wert sollte "False" sein.<br>
![Bildschirmfoto vom 2019-09-10 13-39-42](https://user-images.githubusercontent.com/38523407/64610992-b4b61180-d3d0-11e9-9a21-04b63ca692bf.png)

------------------------------------
QGIS-Version | 3.4.9-Madeira
QGIS-Codeversion | 54585165bb

**Comment by bjsvwcur** [comment]
Anderes Beispiel:
Attribut "rechtsvorschrift":<br>
![grafik](https://user-images.githubusercontent.com/38523407/64611120-02327e80-d3d1-11e9-823b-fa0a69934a20.png)

Wert = "true" wird angezeigt. Wert = "false" wird nicht angezeigt:<br>
![grafik](https://user-images.githubusercontent.com/38523407/64611378-956bb400-d3d1-11e9-8fe4-ed1b79f238d9.png)

Screen aus der Datenbank:  <br>
![Bildschirmfoto vom 2019-09-10 13-44-52](https://user-images.githubusercontent.com/38523407/64611310-6f461400-d3d1-11e9-8ea6-b38b43ee3d80.png)

**Comment by m-kuhn** [comment]
Bestätigt, Danke für das Melden.
Schauen wir uns an.

**Comment by 3nids** [comment]
Pull request is pending for QGIS master https://github.com/qgis/QGIS/pull/31963

**Comment by 3nids** [comment]
merged in master and in 3.4.
Will be released in 3.4.13 and 3.10

**Comment by bjsvwcur** [comment]
Super und danke!
